### ISSUE TITLE
URL 404

### ISSUE THREAD

**Issue by Den5** [microsoft/azure-software-radio-hello-world#24]
Hi 

Great walk through but the Hyperlink below is broken:

As a reference, the completed flowgraph can be found in [flowgraphs/my_first_flowgraph.grc](https://github.com/microsoft/azure-software-radio-hello-world/blob/main/exploring_grc/flowgraphs/my_first_flowgraph.grc) within this repo.

I think it should be:

As a reference, the completed flowgraph can be found in [flowgraphs/my_first_flowgraph.grc](https://github.com/microsoft/azure-software-radio-hello-world/blob/main/exploring_grc/flowgraphs/my_first_flowgraph_complete.grc) within this repo.

Alternatively the file names  in https://github.com/microsoft/azure-software-radio-hello-world/tree/main/exploring_grc/flowgraphs
Could be changed. 

from:
"my_first_flowgraph_complete.grc"

to 

"my_first_flowgraph.grc"

I would like to make a Pull request and Edit, not done many so this would help me get going :)

Denis

**Comment by 777arc** [comment]
Nice catch, I fixed it, but we actually moved the tutorials to https://github.com/microsoft/azure-software-radio so this was also a nice reminder that we should archive this repo and redirect people to where it now lives (don't worry, none of the tutorials actually changed since the move, so you still did the most up-to-date ones).
